/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package it.sasabz.sasabus.opendata.client.model;


public class SASAbusOpenDataMarshaller_Helper extends bz.davide.dmxmljson.marshalling.Marshaller
{
   protected SASAbusOpenDataMarshaller_Helper()
   {
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusLineList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusLineList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusLine[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusLine[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusLine", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusStationList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusStationList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               java.util.ArrayList arrayList = (java.util.ArrayList)value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(arrayList.size());        
               for (Object o: arrayList) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                  else                                                        
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusStation", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.StartDateList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.StartDateList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.StartDate[] rawarray = (it.sasabz.sasabus.opendata.client.model.StartDate[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.StartDate", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusTripStartList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusTripStartLine[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusTripStartLine[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusTripStartLine", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusDayTypeList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusDayTypeList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusDayType[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusDayType[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusDayType", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusPathList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusPathList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusPathLine[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusPathLine[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusPathLine", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStopsList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStopsList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStops[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStops[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStops", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStopsList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStopsList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStops[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStops[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStops", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStopList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStopList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStop[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStop[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStop", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStopList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStopList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStop[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStop[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStop", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStopList", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // list
            value = ((it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStopList)obj).list;
            if (value == null)
               structure.property("list").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("list").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusLine", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // LI_KUERZEL
            value = ((it.sasabz.sasabus.opendata.client.model.BusLine)obj).LI_KUERZEL;
            if (value == null)
               structure.property("LI_KUERZEL").nullValue();
            else
            {
                    structure.property("LI_KUERZEL").string((String)value);                          
            }
            // LI_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusLine)obj).LI_NR;
            if (value == null)
               structure.property("LI_NR").nullValue();
            else
            {
                    structure.property("LI_NR").integer((Integer)value);                          
            }
            // varlist
            value = ((it.sasabz.sasabus.opendata.client.model.BusLine)obj).varlist;
            if (value == null)
               structure.property("varlist").nullValue();
            else
            {
               java.lang.Integer[] rawarray = (java.lang.Integer[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("varlist").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                  else   array.item().integer((Integer)o); 
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusStation", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // ORT_NAME
            value = ((it.sasabz.sasabus.opendata.client.model.BusStation)obj).ORT_NAME;
            if (value == null)
               structure.property("ORT_NAME").nullValue();
            else
            {
                    structure.property("ORT_NAME").string((String)value);                          
            }
            // busLineIds
            value = ((it.sasabz.sasabus.opendata.client.model.BusStation)obj).busLineIds;
            if (value == null)
               structure.property("busLineIds").nullValue();
            else
            {
               java.util.ArrayList arrayList = (java.util.ArrayList)value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("busLineIds").array(arrayList.size());        
               for (Object o: arrayList) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                  else                                                        
                     array.item().integer((Integer)o);                          
               }                                                              
            }
            // busstops
            value = ((it.sasabz.sasabus.opendata.client.model.BusStation)obj).busstops;
            if (value == null)
               structure.property("busstops").nullValue();
            else
            {
               java.util.ArrayList arrayList = (java.util.ArrayList)value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("busstops").array(arrayList.size());        
               for (Object o: arrayList) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                  else                                                        
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusStop", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.StartDate", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // VER_GUELTIGKEIT
            value = ((it.sasabz.sasabus.opendata.client.model.StartDate)obj).VER_GUELTIGKEIT;
            if (value == null)
               structure.property("VER_GUELTIGKEIT").nullValue();
            else
            {
                    structure.property("VER_GUELTIGKEIT").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusTripStartLine", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // LI_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartLine)obj).LI_NR;
            if (value == null)
               structure.property("LI_NR").nullValue();
            else
            {
                    structure.property("LI_NR").integer((Integer)value);                          
            }
            // tagesartlist
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartLine)obj).tagesartlist;
            if (value == null)
               structure.property("tagesartlist").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusTripStartDayType[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusTripStartDayType[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("tagesartlist").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusTripStartDayType", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusDayType", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // BETRIEBSTAG
            value = ((it.sasabz.sasabus.opendata.client.model.BusDayType)obj).BETRIEBSTAG;
            if (value == null)
               structure.property("BETRIEBSTAG").nullValue();
            else
            {
                    structure.property("BETRIEBSTAG").string((String)value);                          
            }
            // TAGESART_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusDayType)obj).TAGESART_NR;
            if (value == null)
               structure.property("TAGESART_NR").nullValue();
            else
            {
                    structure.property("TAGESART_NR").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusPathLine", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // LI_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusPathLine)obj).LI_NR;
            if (value == null)
               structure.property("LI_NR").nullValue();
            else
            {
                    structure.property("LI_NR").string((String)value);                          
            }
            // varlist
            value = ((it.sasabz.sasabus.opendata.client.model.BusPathLine)obj).varlist;
            if (value == null)
               structure.property("varlist").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusPathVariant[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusPathVariant[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("varlist").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusPathVariant", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStops", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // FGR_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStops)obj).FGR_NR;
            if (value == null)
               structure.property("FGR_NR").nullValue();
            else
            {
                    structure.property("FGR_NR").string((String)value);                          
            }
            // ORT_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStops)obj).ORT_NR;
            if (value == null)
               structure.property("ORT_NR").nullValue();
            else
            {
                    structure.property("ORT_NR").string((String)value);                          
            }
            // SEL_FZT
            value = ((it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStops)obj).SEL_FZT;
            if (value == null)
               structure.property("SEL_FZT").nullValue();
            else
            {
                    structure.property("SEL_FZT").string((String)value);                          
            }
            // SEL_ZIEL
            value = ((it.sasabz.sasabus.opendata.client.model.BusStandardTimeBetweenStops)obj).SEL_ZIEL;
            if (value == null)
               structure.property("SEL_ZIEL").nullValue();
            else
            {
                    structure.property("SEL_ZIEL").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStops", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // FRT_FID
            value = ((it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStops)obj).FRT_FID;
            if (value == null)
               structure.property("FRT_FID").nullValue();
            else
            {
                    structure.property("FRT_FID").string((String)value);                          
            }
            // FRT_FZT_ZEIT
            value = ((it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStops)obj).FRT_FZT_ZEIT;
            if (value == null)
               structure.property("FRT_FZT_ZEIT").nullValue();
            else
            {
                    structure.property("FRT_FZT_ZEIT").string((String)value);                          
            }
            // ORT_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusExceptionTimeBetweenStops)obj).ORT_NR;
            if (value == null)
               structure.property("ORT_NR").nullValue();
            else
            {
                    structure.property("ORT_NR").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStop", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // FRT_FID
            value = ((it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStop)obj).FRT_FID;
            if (value == null)
               structure.property("FRT_FID").nullValue();
            else
            {
                    structure.property("FRT_FID").string((String)value);                          
            }
            // FRT_HZT_ZEIT
            value = ((it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStop)obj).FRT_HZT_ZEIT;
            if (value == null)
               structure.property("FRT_HZT_ZEIT").nullValue();
            else
            {
                    structure.property("FRT_HZT_ZEIT").string((String)value);                          
            }
            // ORT_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusWaitTimeAtStop)obj).ORT_NR;
            if (value == null)
               structure.property("ORT_NR").nullValue();
            else
            {
                    structure.property("ORT_NR").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStop", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // FGR_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStop)obj).FGR_NR;
            if (value == null)
               structure.property("FGR_NR").nullValue();
            else
            {
                    structure.property("FGR_NR").string((String)value);                          
            }
            // HP_HZT
            value = ((it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStop)obj).HP_HZT;
            if (value == null)
               structure.property("HP_HZT").nullValue();
            else
            {
                    structure.property("HP_HZT").string((String)value);                          
            }
            // ORT_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusDefaultWaitTimeAtStop)obj).ORT_NR;
            if (value == null)
               structure.property("ORT_NR").nullValue();
            else
            {
                    structure.property("ORT_NR").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // FGR_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop)obj).FGR_NR;
            if (value == null)
               structure.property("FGR_NR").nullValue();
            else
            {
                    structure.property("FGR_NR").string((String)value);                          
            }
            // LIVAR_HZT_ZEIT
            value = ((it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop)obj).LIVAR_HZT_ZEIT;
            if (value == null)
               structure.property("LIVAR_HZT_ZEIT").nullValue();
            else
            {
                    structure.property("LIVAR_HZT_ZEIT").string((String)value);                          
            }
            // LI_LFD_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop)obj).LI_LFD_NR;
            if (value == null)
               structure.property("LI_LFD_NR").nullValue();
            else
            {
                    structure.property("LI_LFD_NR").string((String)value);                          
            }
            // LI_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop)obj).LI_NR;
            if (value == null)
               structure.property("LI_NR").nullValue();
            else
            {
                    structure.property("LI_NR").string((String)value);                          
            }
            // ORT_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop)obj).ORT_NR;
            if (value == null)
               structure.property("ORT_NR").nullValue();
            else
            {
                    structure.property("ORT_NR").string((String)value);                          
            }
            // STR_LI_VAR
            value = ((it.sasabz.sasabus.opendata.client.model.BusLineWaitTimeAtStop)obj).STR_LI_VAR;
            if (value == null)
               structure.property("STR_LI_VAR").nullValue();
            else
            {
                    structure.property("STR_LI_VAR").string((String)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusStop", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // ORT_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusStop)obj).ORT_NR;
            if (value == null)
               structure.property("ORT_NR").nullValue();
            else
            {
                    structure.property("ORT_NR").integer((Integer)value);                          
            }
            // ORT_POS_BREITE
            value = ((it.sasabz.sasabus.opendata.client.model.BusStop)obj).ORT_POS_BREITE;
            if (value == null)
               structure.property("ORT_POS_BREITE").nullValue();
            else
            {
                    structure.property("ORT_POS_BREITE").decimal((Double)value);                          
            }
            // ORT_POS_LAENGE
            value = ((it.sasabz.sasabus.opendata.client.model.BusStop)obj).ORT_POS_LAENGE;
            if (value == null)
               structure.property("ORT_POS_LAENGE").nullValue();
            else
            {
                    structure.property("ORT_POS_LAENGE").decimal((Double)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusTripStartDayType", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // TAGESART_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartDayType)obj).TAGESART_NR;
            if (value == null)
               structure.property("TAGESART_NR").nullValue();
            else
            {
                    structure.property("TAGESART_NR").integer((Integer)value);                          
            }
            // varlist
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartDayType)obj).varlist;
            if (value == null)
               structure.property("varlist").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusTripStartVariant[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusTripStartVariant[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("varlist").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusTripStartVariant", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusPathVariant", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // STR_LI_VAR
            value = ((it.sasabz.sasabus.opendata.client.model.BusPathVariant)obj).STR_LI_VAR;
            if (value == null)
               structure.property("STR_LI_VAR").nullValue();
            else
            {
                    structure.property("STR_LI_VAR").integer((Integer)value);                          
            }
            // routelist
            value = ((it.sasabz.sasabus.opendata.client.model.BusPathVariant)obj).routelist;
            if (value == null)
               structure.property("routelist").nullValue();
            else
            {
               java.lang.Integer[] rawarray = (java.lang.Integer[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("routelist").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                  else   array.item().integer((Integer)o); 
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusTripStartVariant", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // STR_LI_VAR
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartVariant)obj).STR_LI_VAR;
            if (value == null)
               structure.property("STR_LI_VAR").nullValue();
            else
            {
                    structure.property("STR_LI_VAR").integer((Integer)value);                          
            }
            // triplist
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartVariant)obj).triplist;
            if (value == null)
               structure.property("triplist").nullValue();
            else
            {
               it.sasabz.sasabus.opendata.client.model.BusTripStartTime[] rawarray = (it.sasabz.sasabus.opendata.client.model.BusTripStartTime[])value;                        
               bz.davide.dmxmljson.marshalling.Array array = structure.property("triplist").array(rawarray.length);        
               for (Object o: rawarray) {                                    
                  if (o == null)                                              
                     array.item().nullValue();                                
                     internalMarschall(o, o.getClass().getName(), "it.sasabz.sasabus.opendata.client.model.BusTripStartTime", array.item().structure(), identities, seq, false);
               }                                                              
            }
            if (!superClass)
               structure.close();
         }
      });
      this.putClassMarshaller("it.sasabz.sasabus.opendata.client.model.BusTripStartTime", new bz.davide.dmxmljson.marshalling.ClassMarshaller() {
         @Override public void marshall(Object obj, String compileTimeClassName, bz.davide.dmxmljson.marshalling.Structure structure, java.util.IdentityHashMap<Object, bz.davide.dmxmljson.marshalling.Structure> identities, long[] seq, boolean superClass) throws Exception {
            if (!superClass) {
               if (isReference(structure, obj, identities, seq))
                  return;
               identities.put(obj, structure);
               structure.open(shortName(compileTimeClassName), shortName(obj.getClass().getName()), null);
            }
            Object value;
            // FGR_NR
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartTime)obj).FGR_NR;
            if (value == null)
               structure.property("FGR_NR").nullValue();
            else
            {
                    structure.property("FGR_NR").integer((Integer)value);                          
            }
            // FRT_FID
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartTime)obj).FRT_FID;
            if (value == null)
               structure.property("FRT_FID").nullValue();
            else
            {
                    structure.property("FRT_FID").integer((Integer)value);                          
            }
            // FRT_START
            value = ((it.sasabz.sasabus.opendata.client.model.BusTripStartTime)obj).FRT_START;
            if (value == null)
               structure.property("FRT_START").nullValue();
            else
            {
                    structure.property("FRT_START").integer((Integer)value);                          
            }
            if (!superClass)
               structure.close();
         }
      });

   }
}
